package com.kantega.passkeydemo.model.entity

import jakarta.persistence.*
import java.util.*

@Entity
@Table(name = "credentials")
class Credential(
    @Column(nullable = false, unique = true, columnDefinition = "VARBINARY(1024)")
    val credentialId: ByteArray,

    @Column(nullable = false, columnDefinition = "BLOB")
    val publicKey: ByteArray,

    @Column(nullable = false)
    var counter: Long,

    // How the browser can reach the authenticator: "internal", "hybrid", "usb", "nfc", "ble"
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "credential_transports", joinColumns = [JoinColumn(name = "credential_id")])
    @Column(name = "transport")
    val transports: Set<String> = emptySet(),

    // Backup eligible: the passkey can be synced between devices (e.g. iCloud Keychain).
    // Fixed for the lifetime of the credential.
    @Column(nullable = false)
    val backupEligible: Boolean,

    // Backup state: the passkey is currently synced. Can change, so it is updated on every login.
    @Column(nullable = false)
    var backupState: Boolean,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    val user: User
) {
    // Generated by Hibernate when the credential is saved
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    var id: UUID? = null
}
