package com.kantega.passkeydemo.model.entity

import jakarta.persistence.*
import java.util.*

@Entity
@Table(name = "users")
class User(
    @Column(unique = true, nullable = false)
    val username: String,  // email

    @Column(nullable = false)
    var name: String,

    // WebAuthn user handle (user.id in the registration options). Random bytes without personal
    // information, as recommended by the spec. Returned by the authenticator on login.
    @Column(nullable = false, unique = true, columnDefinition = "VARBINARY(64)")
    val userHandle: ByteArray
) {
    // Generated by Hibernate when the user is saved
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    var id: UUID? = null

    @OneToMany(mappedBy = "user", cascade = [CascadeType.ALL], orphanRemoval = true, fetch = FetchType.EAGER)
    val credentials: MutableList<Credential> = mutableListOf()
}
